#!/bin/sh
set -eu

ROOT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
STATE_DIR=${PAYMENT_PROXY_DEPLOY_STATE_DIR:-"$ROOT_DIR/.deploy"}
ENV_FILE="$STATE_DIR/production.env"
TLS_DIR="$STATE_DIR/tls"
COMPOSE_FILE="$ROOT_DIR/docker-compose.production.yml"

usage() {
  echo "Usage:"
  echo "  $0 init <payment-domain> [emisell-callback-url]"
  echo "  $0 deploy <payment-domain> [emisell-callback-url]"
  echo "  $0 deploy"
  echo "  $0 validate"
  echo "  $0 status"
  echo "  $0 logs [service]"
  echo "  $0 credentials"
  echo "  $0 down"
}

fail() {
  echo "ERROR: $*" >&2
  exit 1
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || fail "$1 is required"
}

validate_domain() {
  value=$1
  [ -n "$value" ] || fail "payment domain is required on the first deployment"
  [ "$(printf '%s' "$value" | wc -l | tr -d ' ')" -eq 0 ] || fail "payment domain must be one line"
  printf '%s\n' "$value" | grep -Eq '^[A-Za-z0-9][A-Za-z0-9.-]*[A-Za-z0-9]$' || fail "payment domain must be a hostname without scheme or path"
  case "$value" in
    *..*|.*|*.) fail "payment domain is invalid" ;;
  esac
}

validate_callback() {
  value=$1
  [ -z "$value" ] && return 0
  [ "$(printf '%s' "$value" | wc -l | tr -d ' ')" -eq 0 ] || fail "Emisell callback URL must be one line"
  printf '%s\n' "$value" | grep -Eq '^https://[A-Za-z0-9][A-Za-z0-9.-]*(:[0-9]+)?(/[A-Za-z0-9._~/%+-]*)?$' \
    || fail "Emisell callback URL must be a plain https:// URL without query or fragment"
}

random_hex() {
  openssl rand -hex "$1"
}

base64_file() {
  openssl base64 -A -in "$1"
}

generate_connector_certificate() {
  service_name=$1
  prefix=$2
  extension_file="$TLS_DIR/$prefix.ext"
  openssl req -new -newkey rsa:2048 -nodes \
    -keyout "$TLS_DIR/$prefix.key" \
    -out "$TLS_DIR/$prefix.csr" \
    -subj "/CN=$service_name" >/dev/null 2>&1
  printf '%s\n' \
    "subjectAltName=DNS:$service_name" \
    "extendedKeyUsage=serverAuth" \
    "keyUsage=digitalSignature,keyEncipherment" > "$extension_file"
  openssl x509 -req \
    -in "$TLS_DIR/$prefix.csr" \
    -CA "$TLS_DIR/connector-ca.crt" \
    -CAkey "$TLS_DIR/connector-ca.key" \
    -CAcreateserial \
    -out "$TLS_DIR/$prefix.crt" \
    -days 825 -sha256 -extfile "$extension_file" >/dev/null 2>&1
  rm -f "$TLS_DIR/$prefix.csr" "$extension_file"
}

generate_tls_material() {
  mkdir -p "$TLS_DIR"
  openssl req -x509 -new -newkey rsa:3072 -nodes \
    -keyout "$TLS_DIR/connector-ca.key" \
    -out "$TLS_DIR/connector-ca.crt" \
    -subj "/CN=Emisell Payment Proxy Connector CA" \
    -days 3650 -sha256 >/dev/null 2>&1
  generate_connector_certificate connector-runner xendit
  generate_connector_certificate midtrans-provider-app midtrans
  generate_connector_certificate duitku-provider-app duitku
  generate_connector_certificate doku-provider-app doku
  generate_connector_certificate ipaymu-provider-app ipaymu
  chmod 600 "$TLS_DIR"/*.key
  chmod 644 "$TLS_DIR"/*.crt
}

load_existing_environment() {
  if [ -f "$ENV_FILE" ]; then
    set -a
    # This file is generated by this script and is never committed.
    . "$ENV_FILE"
    set +a
    return 0
  fi
  return 1
}

write_environment() {
  domain=$1
  callback=$2
  umask 077
  mkdir -p "$STATE_DIR"
  chmod 700 "$STATE_DIR"

  POSTGRES_DB=${POSTGRES_DB:-payment_proxy}
  POSTGRES_USER=${POSTGRES_USER:-payment_proxy}
  POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-$(random_hex 24)}
  DATABASE_URL="postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$POSTGRES_DB?sslmode=disable"
  CREDENTIAL_ENCRYPTION_KEY=${CREDENTIAL_ENCRYPTION_KEY:-$(openssl rand -base64 32 | tr -d '\n')}
  SERVICE_API_KEY=${SERVICE_API_KEY:-$(random_hex 32)}
  ADMIN_API_KEY=${ADMIN_API_KEY:-$(random_hex 32)}
  CONNECTOR_RUNNER_TOKEN=${CONNECTOR_RUNNER_TOKEN:-$(random_hex 32)}
  MIDTRANS_PROVIDER_APP_TOKEN=${MIDTRANS_PROVIDER_APP_TOKEN:-$(random_hex 32)}
  DUITKU_PROVIDER_APP_TOKEN=${DUITKU_PROVIDER_APP_TOKEN:-$(random_hex 32)}
  DOKU_PROVIDER_APP_TOKEN=${DOKU_PROVIDER_APP_TOKEN:-$(random_hex 32)}
  IPAYMU_PROVIDER_APP_TOKEN=${IPAYMU_PROVIDER_APP_TOKEN:-$(random_hex 32)}
  DASHBOARD_ADMIN_PASSWORD=${DASHBOARD_ADMIN_PASSWORD:-$(random_hex 16)}
  DASHBOARD_SESSION_SECRET=${DASHBOARD_SESSION_SECRET:-$(random_hex 32)}
  EMISELL_BACKEND_WEBHOOK_SECRET=${EMISELL_BACKEND_WEBHOOK_SECRET:-whsec_$(random_hex 32)}

  if [ -z "${CONNECTOR_TLS_CA_BASE64:-}" ]; then
    generate_tls_material
    CONNECTOR_TLS_CA_BASE64=$(base64_file "$TLS_DIR/connector-ca.crt")
    XENDIT_CONNECTOR_TLS_CERT_BASE64=$(base64_file "$TLS_DIR/xendit.crt")
    XENDIT_CONNECTOR_TLS_KEY_BASE64=$(base64_file "$TLS_DIR/xendit.key")
    MIDTRANS_CONNECTOR_TLS_CERT_BASE64=$(base64_file "$TLS_DIR/midtrans.crt")
    MIDTRANS_CONNECTOR_TLS_KEY_BASE64=$(base64_file "$TLS_DIR/midtrans.key")
    DUITKU_CONNECTOR_TLS_CERT_BASE64=$(base64_file "$TLS_DIR/duitku.crt")
    DUITKU_CONNECTOR_TLS_KEY_BASE64=$(base64_file "$TLS_DIR/duitku.key")
    DOKU_CONNECTOR_TLS_CERT_BASE64=$(base64_file "$TLS_DIR/doku.crt")
    DOKU_CONNECTOR_TLS_KEY_BASE64=$(base64_file "$TLS_DIR/doku.key")
    IPAYMU_CONNECTOR_TLS_CERT_BASE64=$(base64_file "$TLS_DIR/ipaymu.crt")
    IPAYMU_CONNECTOR_TLS_KEY_BASE64=$(base64_file "$TLS_DIR/ipaymu.key")
  elif { [ -z "${DUITKU_CONNECTOR_TLS_CERT_BASE64:-}" ] || [ -z "${DUITKU_CONNECTOR_TLS_KEY_BASE64:-}" ] || [ -z "${DOKU_CONNECTOR_TLS_CERT_BASE64:-}" ] || [ -z "${DOKU_CONNECTOR_TLS_KEY_BASE64:-}" ] || [ -z "${IPAYMU_CONNECTOR_TLS_CERT_BASE64:-}" ] || [ -z "${IPAYMU_CONNECTOR_TLS_KEY_BASE64:-}" ]; } && { [ ! -f "$TLS_DIR/connector-ca.crt" ] || [ ! -f "$TLS_DIR/connector-ca.key" ]; }; then
    generate_tls_material
    CONNECTOR_TLS_CA_BASE64=$(base64_file "$TLS_DIR/connector-ca.crt")
    XENDIT_CONNECTOR_TLS_CERT_BASE64=$(base64_file "$TLS_DIR/xendit.crt")
    XENDIT_CONNECTOR_TLS_KEY_BASE64=$(base64_file "$TLS_DIR/xendit.key")
    MIDTRANS_CONNECTOR_TLS_CERT_BASE64=$(base64_file "$TLS_DIR/midtrans.crt")
    MIDTRANS_CONNECTOR_TLS_KEY_BASE64=$(base64_file "$TLS_DIR/midtrans.key")
    DUITKU_CONNECTOR_TLS_CERT_BASE64=$(base64_file "$TLS_DIR/duitku.crt")
    DUITKU_CONNECTOR_TLS_KEY_BASE64=$(base64_file "$TLS_DIR/duitku.key")
    DOKU_CONNECTOR_TLS_CERT_BASE64=$(base64_file "$TLS_DIR/doku.crt")
    DOKU_CONNECTOR_TLS_KEY_BASE64=$(base64_file "$TLS_DIR/doku.key")
    IPAYMU_CONNECTOR_TLS_CERT_BASE64=$(base64_file "$TLS_DIR/ipaymu.crt")
    IPAYMU_CONNECTOR_TLS_KEY_BASE64=$(base64_file "$TLS_DIR/ipaymu.key")
  else
    if [ -z "${DUITKU_CONNECTOR_TLS_CERT_BASE64:-}" ] || [ -z "${DUITKU_CONNECTOR_TLS_KEY_BASE64:-}" ]; then
      generate_connector_certificate duitku-provider-app duitku
      chmod 600 "$TLS_DIR/duitku.key"
      chmod 644 "$TLS_DIR/duitku.crt"
      DUITKU_CONNECTOR_TLS_CERT_BASE64=$(base64_file "$TLS_DIR/duitku.crt")
      DUITKU_CONNECTOR_TLS_KEY_BASE64=$(base64_file "$TLS_DIR/duitku.key")
    fi
    if [ -z "${DOKU_CONNECTOR_TLS_CERT_BASE64:-}" ] || [ -z "${DOKU_CONNECTOR_TLS_KEY_BASE64:-}" ]; then
      generate_connector_certificate doku-provider-app doku
      chmod 600 "$TLS_DIR/doku.key"
      chmod 644 "$TLS_DIR/doku.crt"
      DOKU_CONNECTOR_TLS_CERT_BASE64=$(base64_file "$TLS_DIR/doku.crt")
      DOKU_CONNECTOR_TLS_KEY_BASE64=$(base64_file "$TLS_DIR/doku.key")
    fi
    if [ -z "${IPAYMU_CONNECTOR_TLS_CERT_BASE64:-}" ] || [ -z "${IPAYMU_CONNECTOR_TLS_KEY_BASE64:-}" ]; then
      generate_connector_certificate ipaymu-provider-app ipaymu
      chmod 600 "$TLS_DIR/ipaymu.key"
      chmod 644 "$TLS_DIR/ipaymu.crt"
      IPAYMU_CONNECTOR_TLS_CERT_BASE64=$(base64_file "$TLS_DIR/ipaymu.crt")
      IPAYMU_CONNECTOR_TLS_KEY_BASE64=$(base64_file "$TLS_DIR/ipaymu.key")
    fi
  fi

  temp_file="$ENV_FILE.tmp"
  {
    echo "IMAGE_TAG=production"
    echo "POSTGRES_IMAGE=postgres:17-alpine"
    echo "PAYMENT_PROXY_DOMAIN=$domain"
    echo "POSTGRES_DB=$POSTGRES_DB"
    echo "POSTGRES_USER=$POSTGRES_USER"
    echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD"
    echo "DATABASE_URL=$DATABASE_URL"
    echo "CREDENTIAL_ENCRYPTION_KEY=$CREDENTIAL_ENCRYPTION_KEY"
    echo "SERVICE_API_KEY=$SERVICE_API_KEY"
    echo "ADMIN_API_KEY=$ADMIN_API_KEY"
    echo "CONNECTOR_RUNNER_TOKEN=$CONNECTOR_RUNNER_TOKEN"
    echo "MIDTRANS_PROVIDER_APP_TOKEN=$MIDTRANS_PROVIDER_APP_TOKEN"
    echo "DUITKU_PROVIDER_APP_TOKEN=$DUITKU_PROVIDER_APP_TOKEN"
    echo "DOKU_PROVIDER_APP_TOKEN=$DOKU_PROVIDER_APP_TOKEN"
    echo "IPAYMU_PROVIDER_APP_TOKEN=$IPAYMU_PROVIDER_APP_TOKEN"
    echo "CONNECTOR_TLS_CA_BASE64=$CONNECTOR_TLS_CA_BASE64"
    echo "XENDIT_CONNECTOR_TLS_CERT_BASE64=$XENDIT_CONNECTOR_TLS_CERT_BASE64"
    echo "XENDIT_CONNECTOR_TLS_KEY_BASE64=$XENDIT_CONNECTOR_TLS_KEY_BASE64"
    echo "MIDTRANS_CONNECTOR_TLS_CERT_BASE64=$MIDTRANS_CONNECTOR_TLS_CERT_BASE64"
    echo "MIDTRANS_CONNECTOR_TLS_KEY_BASE64=$MIDTRANS_CONNECTOR_TLS_KEY_BASE64"
    echo "DUITKU_CONNECTOR_TLS_CERT_BASE64=$DUITKU_CONNECTOR_TLS_CERT_BASE64"
    echo "DUITKU_CONNECTOR_TLS_KEY_BASE64=$DUITKU_CONNECTOR_TLS_KEY_BASE64"
    echo "DOKU_CONNECTOR_TLS_CERT_BASE64=$DOKU_CONNECTOR_TLS_CERT_BASE64"
    echo "DOKU_CONNECTOR_TLS_KEY_BASE64=$DOKU_CONNECTOR_TLS_KEY_BASE64"
    echo "IPAYMU_CONNECTOR_TLS_CERT_BASE64=$IPAYMU_CONNECTOR_TLS_CERT_BASE64"
    echo "IPAYMU_CONNECTOR_TLS_KEY_BASE64=$IPAYMU_CONNECTOR_TLS_KEY_BASE64"
    echo "DASHBOARD_MERCHANT_ID=${DASHBOARD_MERCHANT_ID:-payment_proxy_operator}"
    echo "DASHBOARD_ADMIN_PASSWORD=$DASHBOARD_ADMIN_PASSWORD"
    echo "DASHBOARD_SESSION_SECRET=$DASHBOARD_SESSION_SECRET"
    echo "EMISELL_BACKEND_WEBHOOK_URL=$callback"
    echo "EMISELL_BACKEND_WEBHOOK_SECRET=$EMISELL_BACKEND_WEBHOOK_SECRET"
  } > "$temp_file"
  chmod 600 "$temp_file"
  mv "$temp_file" "$ENV_FILE"
}

compose() {
  docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" "$@"
}

command=${1:-deploy}
case "$command" in
  init)
    require_command docker
    require_command openssl
    existing_domain=""
    existing_callback=""
    if load_existing_environment; then
      existing_domain=${PAYMENT_PROXY_DOMAIN:-}
      existing_callback=${EMISELL_BACKEND_WEBHOOK_URL:-}
    fi
    domain=${2:-$existing_domain}
    callback=${3:-$existing_callback}
    validate_domain "$domain"
    validate_callback "$callback"
    write_environment "$domain" "$callback"
    compose config --quiet
    echo "Production deployment initialized for https://$domain"
    ;;
  deploy)
    require_command docker
    require_command openssl
    created=false
    existing_domain=""
    existing_callback=""
    if load_existing_environment; then
      existing_domain=${PAYMENT_PROXY_DOMAIN:-}
      existing_callback=${EMISELL_BACKEND_WEBHOOK_URL:-}
    else
      created=true
    fi
    domain=${2:-$existing_domain}
    callback=${3:-$existing_callback}
    validate_domain "$domain"
    validate_callback "$callback"
    write_environment "$domain" "$callback"
    compose config --quiet
    if docker compose up --help | grep -q -- '--wait'; then
      compose up -d --build --remove-orphans --wait --wait-timeout 240
    else
      compose up -d --build --remove-orphans
    fi
    compose ps
    echo ""
    echo "Deployment ready: https://$domain"
    if [ "$created" = true ]; then
      echo "Dashboard admin password was generated automatically."
      echo "Run '$0 credentials' on this server to view integration credentials."
    fi
    ;;
  validate)
    [ -f "$ENV_FILE" ] || fail "deployment has not been initialized"
    compose config --quiet
    echo "Production Compose configuration is valid."
    ;;
  status)
    [ -f "$ENV_FILE" ] || fail "deployment has not been initialized"
    compose ps
    ;;
  logs)
    [ -f "$ENV_FILE" ] || fail "deployment has not been initialized"
    if [ "$#" -ge 2 ]; then
      compose logs -f --tail=200 "$2"
    else
      compose logs -f --tail=200
    fi
    ;;
  credentials)
    [ -f "$ENV_FILE" ] || fail "deployment has not been initialized"
    load_existing_environment
    echo "Dashboard URL: https://$PAYMENT_PROXY_DOMAIN"
    echo "Dashboard admin password: $DASHBOARD_ADMIN_PASSWORD"
    echo "Emisell Backend service API key: $SERVICE_API_KEY"
    echo "Emisell webhook signing secret: $EMISELL_BACKEND_WEBHOOK_SECRET"
    ;;
  down)
    [ -f "$ENV_FILE" ] || fail "deployment has not been initialized"
    compose down
    ;;
  help|-h|--help)
    usage
    ;;
  *)
    usage
    exit 1
    ;;
esac
